### ISSUE TITLE
Building 4.13.1.0 with GHC 8.6.5 fails

### ISSUE THREAD

**Issue by lierdakil** [jaspervdj/hakyll#759]
Trying to build with GHC 8.6.5 here, getting
```
lib/Hakyll/Core/Metadata.hs:69:23: error:
    Not in scope: type constructor or class ‘MonadFail’
   |
69 | getMetadataField' :: (MonadFail m, MonadMetadata m) => Identifier -> String -> m String
   |                       ^^^^^^^^^
```

#754 is probably related.

P.S. Probably just need to `import Control.Monad.Fail`?

**Comment by jaspervdj** [comment]
I started a PR to fix this in #761 but I'm currently traveling so unsure when I'll be able to do a fix/release.

**Comment by jaspervdj** [comment]
Released as `v4.13.2.0`.  Thanks again for reporting & for the fix @lierdakil!
