### PR TITLE
fix building on GHC 7.10

### LINKED ISSUE #343: 4.6.7.1 fails on GHC 7.10: requires FlexibleContexts:
4.6.7.1 fails on GHC 7.10: requires FlexibleContexts:

    [ 8 of 47] Compiling Hakyll.Core.Util.String ( src/Hakyll/Core/Util/String.hs, dist/build/Hakyll/Core/Util/String.o )
    
    src/Hakyll/Core/Util/String.hs:50:5:
        Non type-variable argument
          in the constraint: Text.Regex.Base.RegexLike.RegexLike
                               Text.Regex.TDFA.Common.Regex [a]
        (Use FlexibleContexts to permit this)
        When checking that ‘splitAll'’ has the inferred type
          splitAll' :: forall a.
                       Text.Regex.Base.RegexLike.RegexLike
                         Text.Regex.TDFA.Common.Regex [a] =>
                       [a] -> [[a]]
        In an equation for ‘splitAll’:
            splitAll pattern
              = filter (not . null) . splitAll'
              where
                  splitAll' src
                    = case listToMaybe (src =~~ pattern) of {
                        Nothing -> ...
                        Just (o, l) -> ... }

### PR DESCRIPTION
**Pull request by cstrahan**
With this patch, Hakyll builds on both GHC 7.8.x and 7.10.x. This fixes #343.

### CODE REVIEW

**Comment by cstrahan** [comment]
Hey @jaspervdj, just curious what you think of this PR. Would you like me to change anything?

Note that the CI failure seems to be a configuration problem:

    cabal: Error: some packages failed to install:
    pandoc-1.13.2 failed during the configure step. The exception was:
    user error
    (/usr/local/ghc/7.6.3/lib/ghc-7.6.3/unix-2.6.0.1/libHSunix-2.6.0.1.a(execvpe.o):
    In function `pPrPr_disableITimers':
    execvpe.c:(.text+0x0): multiple definition of `pPrPr_disableITimers'
    /home/travis/.cabal/lib/x86_64-linux-ghc-7.6.3/unix-2.7.1.0/libHSunix-2.7.1.0.a(ghcrts.o):ghcrts.c:(.text+0x0):
    first defined here
    collect2: ld returned 1 exit status
    )
    pandoc-citeproc-0.6 depends on pandoc-1.13.2 which failed to install.
    The command "eval cabal install --only-dependencies --enable-tests" failed. Retrying, 2 of 3.

**Comment by lemol** [comment]
Hi @cstrahan, when I try to build with your branch I get the following error. Am I missing something?
```
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: hakyll-4.6.7.1 (user goal)
trying: process-1.2.3.0/installed-3b1... (dependency of hakyll-4.6.7.1)
next goal: pandoc (dependency of hakyll-4.6.7.1)
rejecting: pandoc-1.13.2, 1.13.1, 1.13.0.1, 1.13, 1.12.4.2, 1.12.4 (conflict:
process => filepath==1.4.0.0/installed-40d..., pandoc => filepath>=1.1 &&
<1.4)
rejecting: pandoc-1.12.3.3, 1.12.3.2, 1.12.3.1, 1.12.3, 1.12.2.1, 1.12.2,
1.12.1, 1.12.0.2, 1.12.0.1, 1.12, 1.11.1, 1.11, 1.10.1, 1.10.0.5, 1.10.0.4,
1.10.0.3, 1.10.0.2, 1.10.0.1, 1.10, 1.9.4.5, 1.9.4.4, 1.9.4.3, 1.9.4.2,
1.9.4.1, 1.9.4, 1.9.3, 1.9.2, 1.9.1.2, 1.9.1.1, 1.9.1, 1.9.0.5, 1.9.0.4,
1.9.0.3, 1.9.0.2, 1.9, 1.8.2.1, 1.8.2, 1.8.1.2, 1.8.1.1, 1.8.1, 1.8.0.3,
1.8.0.2, 1.8.0.1, 1.8, 1.6.0.1, 1.6, 1.5.1.1, 1.5.1, 1.5.0.1, 1.5, 1.4, 1.3,
1.2.1, 1.2, 1.1, 1.0.0.1, 1.0, 0.46, 0.45, 0.44, 0.43, 0.42, 0.41, 0.4
(conflict: hakyll => pandoc>=1.12.4 && <1.14)
Backjump limit reached (change with --max-backjumps).

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.
```

**Comment by jaspervdj** [comment]
Thanks @cstrahan, looks fine to me.

**Comment by jaspervdj** [comment]
Should be on Hackage now.
